# Generated by Django 5.2.8 on 2025-12-17 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "file",
                    models.FileField(
                        upload_to="videos/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "avi", "mov", "mkv", "wmv"]
                            )
                        ],
                        verbose_name="동영상 파일",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="thumbnails/",
                        verbose_name="썸네일",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 일시"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="파일 크기(bytes)"),
                ),
                (
                    "duration",
                    models.FloatField(default=0, verbose_name="재생 시간(초)"),
                ),
            ],
            options={
                "verbose_name": "동영상",
                "verbose_name_plural": "동영상 목록",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
