# Generated by Django 5.2.8 on 2025-12-17 05:45

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "동영상",
                "verbose_name_plural": "동영상들",
            },
        ),
        migrations.RemoveField(
            model_name="video",
            name="duration",
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                upload_to=videos.models.video_upload_path, verbose_name="동영상 파일"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="file_size",
            field=models.BigIntegerField(default=0, verbose_name="파일 크기"),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=videos.models.thumbnail_upload_path,
                verbose_name="썸네일",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="업로드 시간"),
        ),
    ]
