# Generated by Django 5.2.8 on 2025-12-18 05:48

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_video_options_remove_video_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "file",
                    models.ImageField(
                        upload_to=videos.models.image_upload_path,
                        verbose_name="이미지 파일",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="파일 크기"),
                ),
                ("width", models.IntegerField(default=0, verbose_name="너비")),
                ("height", models.IntegerField(default=0, verbose_name="높이")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 시간"),
                ),
            ],
            options={
                "verbose_name": "이미지",
                "verbose_name_plural": "이미지들",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
