# Generated by Django 5.2.8 on 2025-12-17 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="모델 이름")),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("yolo", "YOLO (객체 감지)"),
                            ("custom", "Custom Model"),
                        ],
                        max_length=50,
                        verbose_name="모델 타입",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "model_file",
                    models.FileField(
                        blank=True,
                        help_text="YOLO: .pt 파일, Custom: .pt, .pth, .onnx 등",
                        null=True,
                        upload_to="detection_models/",
                        verbose_name="모델 파일",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="모델 설정"
                    ),
                ),
                (
                    "yolo_version",
                    models.CharField(
                        blank=True,
                        help_text="예: yolov8n.pt, yolov8s.pt, yolov8m.pt",
                        max_length=50,
                        verbose_name="YOLO 버전",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "감지 모델",
                "verbose_name_plural": "감지 모델들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="제목"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "준비"),
                            ("processing", "처리 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="ready",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="진행률")),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="시작 시간"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 시간"
                    ),
                ),
                (
                    "processed_frames",
                    models.IntegerField(default=0, verbose_name="처리된 프레임"),
                ),
                (
                    "total_frames",
                    models.IntegerField(default=0, verbose_name="총 프레임"),
                ),
                (
                    "results_json",
                    models.TextField(blank=True, verbose_name="결과 JSON"),
                ),
                (
                    "output_video_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="출력 동영상 경로"
                    ),
                ),
                (
                    "total_detections",
                    models.IntegerField(default=0, verbose_name="총 감지 수"),
                ),
                (
                    "detection_summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="감지 요약"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="analysis.analysis",
                        verbose_name="분석",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="detection.detectionmodel",
                        verbose_name="사용 모델",
                    ),
                ),
            ],
            options={
                "verbose_name": "감지 작업",
                "verbose_name_plural": "감지 작업들",
                "ordering": ["-created_at"],
            },
        ),
    ]
