# Generated by Django 5.2.8 on 2025-12-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detectionmodel",
            name="model_file",
        ),
        migrations.AddField(
            model_name="detectionmodel",
            name="model_path",
            field=models.CharField(
                blank=True,
                help_text="models/ 디렉토리 기준 상대 경로",
                max_length=500,
                verbose_name="모델 파일 경로",
            ),
        ),
        migrations.AlterField(
            model_name="detectionmodel",
            name="model_type",
            field=models.CharField(
                choices=[("yolo", "YOLO"), ("custom", "Custom Model")],
                max_length=50,
                verbose_name="모델 타입",
            ),
        ),
    ]
