# Generated by Django 5.2.8 on 2025-12-16 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "준비"),
                            ("processing", "처리 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("preprocessing_pipeline", models.JSONField(blank=True, default=list)),
                ("progress", models.IntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=100)),
                ("output_video_path", models.CharField(blank=True, max_length=500)),
                ("result_frames_dir", models.CharField(blank=True, max_length=500)),
                ("total_frames", models.IntegerField(default=0)),
                ("processed_frames", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
