# Generated by Django 5.2.8 on 2025-12-18 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_alter_analysis_video"),
        ("videos", "0003_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysis",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "분석",
                "verbose_name_plural": "분석들",
            },
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="current_step",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="result_frames_dir",
        ),
        migrations.AddField(
            model_name="analysis",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="videos.image",
                verbose_name="이미지",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="완료 시간"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="에러 메시지"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="output_video_path",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="출력 파일 경로"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="preprocessing_pipeline",
            field=models.JSONField(
                blank=True, default=list, verbose_name="전처리 파이프라인"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="processed_frames",
            field=models.IntegerField(default=0, verbose_name="처리된 프레임"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="progress",
            field=models.IntegerField(default=0, verbose_name="진행률 (%)"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="시작 시간"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("ready", "준비"),
                    ("processing", "처리 중"),
                    ("completed", "완료"),
                    ("failed", "실패"),
                ],
                default="ready",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="total_frames",
            field=models.IntegerField(default=0, verbose_name="총 프레임"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="videos.video",
                verbose_name="동영상",
            ),
        ),
    ]
