# Generated by Django 5.2.8 on 2025-12-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analysis",
            "0003_alter_analysis_options_remove_analysis_current_step_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="current_step",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="현재 단계"
            ),
        ),
    ]
