# Generated by Django 5.2.8 on 2025-12-23 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0004_analysis_current_step"),
        ("modelhub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "대기"),
                            ("processing", "처리 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="ready",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "total_frames",
                    models.IntegerField(default=0, verbose_name="총 프레임"),
                ),
                (
                    "processed_frames",
                    models.IntegerField(default=0, verbose_name="처리된 프레임"),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="진행률 (%)")),
                (
                    "output_video_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="결과 동영상 경로"
                    ),
                ),
                (
                    "detection_data",
                    models.JSONField(
                        blank=True, default=list, verbose_name="탐지 데이터"
                    ),
                ),
                (
                    "total_detections",
                    models.IntegerField(default=0, verbose_name="총 탐지 수"),
                ),
                (
                    "detection_summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="탐지 요약"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="시작 시간"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 시간"
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="analysis.analysis",
                        verbose_name="분석",
                    ),
                ),
                (
                    "base_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="modelhub.basemodel",
                        verbose_name="기본 모델",
                    ),
                ),
                (
                    "custom_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="modelhub.custommodel",
                        verbose_name="커스텀 모델",
                    ),
                ),
            ],
            options={
                "verbose_name": "객체 탐지",
                "verbose_name_plural": "객체 탐지들",
                "ordering": ["-created_at"],
            },
        ),
    ]
